<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MACPK-WKS-0132" failures="1" tests="11" name="Master.SepRelease" time="304.071" errors="0" timestamp="06 Nov 2019 12:39:37 GMT" skipped="0">
  <testcase classname="Master.SepRelease" name="LoginIdaho" time="5.938"/>
  <testcase classname="Master.SepRelease" name="CreateCustomerCompany" time="50.770"/>
  <testcase classname="Master.SepRelease" name="AddCompanyNoteTD_963218" time="44.962"/>
  <testcase classname="Master.SepRelease" name="EditCompanyNote" time="21.301"/>
  <testcase classname="Master.SepRelease" name="CreateContactFromMain" time="25.215"/>
  <testcase classname="Master.SepRelease" name="AddingNoteUnderContactTD_" time="29.106"/>
  <testcase classname="Master.SepRelease" name="EditContactNote" time="21.840"/>
  <testcase classname="Master.SepRelease" name="PORefISNULL_93843" time="19.343"/>
  <testcase classname="Master.SepRelease" name="CreateNoteFromMain" time="9.844"/>
  <testcase classname="Master.SepRelease" name="PORefISNOTNULL_93844" time="30.060">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at OrdersTestcases.OctRelease.PORefISNOTNULL(OctRelease.java:73)
at Master.SepRelease.PORefISNOTNULL_93844(SepRelease.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- PORefISNOTNULL_93844 -->
  <testcase classname="Master.SepRelease" name="CreateQuoteFromOrder_93845" time="45.692"/>
</testsuite> <!-- Master.SepRelease -->
